package Day16;

import java.util.Scanner;

public class ExceptionDemo {

	public static void main(String[] args) {
	/*	System.out.println("program is started.....");
		
		
		Scanner sc = new Scanner(System.in);
		
		System.out.println("Enter a num:");
		int num = sc.nextInt();
		
		System.out.println(100/num);
		

		
		
		System.out.println("program is completed..");
		System.out.println("program is exited...");
		
	int a[]= new int[5]; // Array bound out of index exception
		System.out.println("Enter the position(0-4):");
		int pos = sc.nextInt();
		System.out.println("Enter the value:");
		int value = sc.nextInt();
		
		a[pos]=value;
		System.out.println(a[pos]);
		
		String s= "1234";
		int num1 = Integer.parseInt(s);*/
		
		String s1 =null;
		System.out.println(s1.length());
		
		
		

	}

}
